name: jargon_onSnapshot

on:
  repository_dispatch:
    types: [ 'jargon_onSnapshot' ]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event.client_payload) }}'
      
