name: jargon_onSnapshot

on:
  repository_dispatch:
    types: [ 'jargon_onSnapshot' ]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - run: jq -c '. ' < ${{ github.event.client_payload }} >> client_payload.json
      - run: cat client_payload.json
